### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by rubenc57** [dejanstojanovic/jQuery-GoogleMaps#4]
Hello
I'm receiving this error:

"No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:1234' is therefore not allowed access."

Any Ideas?

**Comment by dejanstojanovic** [comment]
Looks like you do not have CORS enabled. Check this thread for help https://forums.asp.net/t/2013856.aspx?enable+CORS+MVC+5
Let me know if it worked for you

**Comment by dejanstojanovic** [comment]
I have something on my blog as well so check that one as well https://dejanstojanovic.net/aspnet/2015/march/enabling-cors-only-for-specific-domains-in-aspnet/

**Comment by rubenc57** [comment]
Nop it didn't work

I still receive the error, this is the full list:

"Failed to load http://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-circle.html: Redirect from 'http://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-circle.html' to 'https://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-circle.html' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5550' is therefore not allowed access.

Failed to load http://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-rectangle.html: Redirect from 'http://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-rectangle.html' to 'https://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-rectangle.html' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5550' is therefore not allowed access.

Failed to load http://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-marker.html: Redirect from 'http://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-marker.html' to 'https://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-marker.html' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5550' is therefore not allowed access.

Failed to load http://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-polyline.html: Redirect from 'http://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-polyline.html' to 'https://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-polyline.html' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5550' is therefore not allowed access.

Failed to load http://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-polygon.html: Redirect from 'http://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-polygon.html' to 'https://rawgit.com/dejanstojanovic/JQuery-GoogleMaps/master/src/html/popup-template-polygon.html' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5550' is therefore not allowed access.

Failed to load resource: the server responded with a status of 404 (Not Found)

Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys"

**Comment by dejanstojanovic** [comment]
I do not get why are you trying to load these from the GitHub?
Why don't you copy all these files to your local and then try to add it to your application. You should not use GitHub as a CDN, it is simply not intended to be one  :)

**Comment by rubenc57** [comment]
I did not make any changes, it was working fine and the next day, is giving me these errors
I don't get it too

**Comment by rubenc57** [comment]
Ok, I had some redirections wrong… now I don't receive the CROS errors

Can you confirm how do I set the api_key?
Now I'm receiving this error:

util.js:225 Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
Ww.j @ util.js:225
(anonymous) @ js?sensor=false&callback=mapApiLoaded&libraries=drawing,places&language=es&_=1536501016111:167
(anonymous) @ js?sensor=false&callback=mapApiLoaded&libraries=drawing,places&language=es&_=1536501016111:72
(anonymous) @ js?sensor=false&callback=mapApiLoaded&libraries=drawing,places&language=es&_=1536501016111:69
(anonymous) @ js?sensor=false&callback=mapApiLoaded&libraries=drawing,places&language=es&_=1536501016111:72
(anonymous) @ js?sensor=false&callback=mapApiLoaded&libraries=drawing,places&language=es&_=1536501016111:146
(anonymous) @ js?sensor=false&callback=mapApiLoaded&libraries=drawing,places&language=es&_=1536501016111:72
(anonymous) @ js?sensor=false&callback=mapApiLoaded&libraries=drawing,places&language=es&_=1536501016111:146
Ae @ js?sensor=false&callback=mapApiLoaded&libraries=drawing,places&language=es&_=1536501016111:71
ue.wa @ js?sensor=false&callback=mapApiLoaded&libraries=drawing,places&language=es&_=1536501016111:146
(anonymous) @ stats.js:1

**Comment by dejanstojanovic** [comment]
As far as I remember you need to create a project with you google account and enable GoogleMaps API. Then you can generate the key. Pretty much standard procedure for any Google API you want to use. 

Check through their documentation, it is pretty easy to acquire a token fro you script. I'll try to find some article that might help, but do check out the Google documentation

**Comment by rubenc57** [comment]
Yeah, I already have that, I meant within your function...

**Comment by rubenc57** [comment]
I get these errors now:

"Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
js?sensor=false&callback=mapApiLoaded&libraries=drawing,places&language=es&_=1536533455178:43 

This service requires an API key.  For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key"

And this url: https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys, says: "The script element that loads the API has no API key. Please make sure you include a valid API key as a key parameter."

So, I have an API key, I just don't know how to include it in your plugin...
I cannot find in your documentation how to include the API key
Please remember that I'm using webforms

**Comment by dejanstojanovic** [comment]
I believe you should supply your key when GoogleMaps API is loaded and the URL for GoogleMaps API JavaScript library is declared in this variable

var mapApiUrl = "//maps.googleapis.com/maps/api/js?sensor=false&callback=mapApiLoaded&libraries=drawing,places"

So just update the variable with the token and it should work

**Comment by rubenc57** [comment]
Thank you, it is working now

**Comment by dejanstojanovic** [comment]
Great, I am closing the issue.
